# Generated by Django 4.2.11 on 2024-04-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="jobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("skills", models.TextField()),
                ("salary", models.CharField(max_length=50)),
                ("posting_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
